server:
  port: 8380

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

