/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.anonyshare.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CommentAttributeUpdatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1854179076772168520L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CommentAttributeUpdatedAvroModel\",\"namespace\":\"com.anonyshare.kafka.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"likesCount\",\"type\":\"int\"},{\"name\":\"dislikeCount\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<CommentAttributeUpdatedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CommentAttributeUpdatedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CommentAttributeUpdatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CommentAttributeUpdatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CommentAttributeUpdatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CommentAttributeUpdatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CommentAttributeUpdatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CommentAttributeUpdatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CommentAttributeUpdatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private int likesCount;
  private int dislikeCount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CommentAttributeUpdatedAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param likesCount The new value for likesCount
   * @param dislikeCount The new value for dislikeCount
   */
  public CommentAttributeUpdatedAvroModel(java.util.UUID id, java.lang.Integer likesCount, java.lang.Integer dislikeCount) {
    this.id = id;
    this.likesCount = likesCount;
    this.dislikeCount = dislikeCount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return likesCount;
    case 2: return dislikeCount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: likesCount = (java.lang.Integer)value$; break;
    case 2: dislikeCount = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'likesCount' field.
   * @return The value of the 'likesCount' field.
   */
  public int getLikesCount() {
    return likesCount;
  }


  /**
   * Sets the value of the 'likesCount' field.
   * @param value the value to set.
   */
  public void setLikesCount(int value) {
    this.likesCount = value;
  }

  /**
   * Gets the value of the 'dislikeCount' field.
   * @return The value of the 'dislikeCount' field.
   */
  public int getDislikeCount() {
    return dislikeCount;
  }


  /**
   * Sets the value of the 'dislikeCount' field.
   * @param value the value to set.
   */
  public void setDislikeCount(int value) {
    this.dislikeCount = value;
  }

  /**
   * Creates a new CommentAttributeUpdatedAvroModel RecordBuilder.
   * @return A new CommentAttributeUpdatedAvroModel RecordBuilder
   */
  public static com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder newBuilder() {
    return new com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder();
  }

  /**
   * Creates a new CommentAttributeUpdatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CommentAttributeUpdatedAvroModel RecordBuilder
   */
  public static com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder newBuilder(com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder other) {
    if (other == null) {
      return new com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder();
    } else {
      return new com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CommentAttributeUpdatedAvroModel RecordBuilder by copying an existing CommentAttributeUpdatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CommentAttributeUpdatedAvroModel RecordBuilder
   */
  public static com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder newBuilder(com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel other) {
    if (other == null) {
      return new com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder();
    } else {
      return new com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CommentAttributeUpdatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CommentAttributeUpdatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<CommentAttributeUpdatedAvroModel> {

    private java.util.UUID id;
    private int likesCount;
    private int dislikeCount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.likesCount)) {
        this.likesCount = data().deepCopy(fields()[1].schema(), other.likesCount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dislikeCount)) {
        this.dislikeCount = data().deepCopy(fields()[2].schema(), other.dislikeCount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CommentAttributeUpdatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.likesCount)) {
        this.likesCount = data().deepCopy(fields()[1].schema(), other.likesCount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dislikeCount)) {
        this.dislikeCount = data().deepCopy(fields()[2].schema(), other.dislikeCount);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'likesCount' field.
      * @return The value.
      */
    public int getLikesCount() {
      return likesCount;
    }


    /**
      * Sets the value of the 'likesCount' field.
      * @param value The value of 'likesCount'.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder setLikesCount(int value) {
      validate(fields()[1], value);
      this.likesCount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'likesCount' field has been set.
      * @return True if the 'likesCount' field has been set, false otherwise.
      */
    public boolean hasLikesCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'likesCount' field.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder clearLikesCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dislikeCount' field.
      * @return The value.
      */
    public int getDislikeCount() {
      return dislikeCount;
    }


    /**
      * Sets the value of the 'dislikeCount' field.
      * @param value The value of 'dislikeCount'.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder setDislikeCount(int value) {
      validate(fields()[2], value);
      this.dislikeCount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dislikeCount' field has been set.
      * @return True if the 'dislikeCount' field has been set, false otherwise.
      */
    public boolean hasDislikeCount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dislikeCount' field.
      * @return This builder.
      */
    public com.anonyshare.kafka.model.CommentAttributeUpdatedAvroModel.Builder clearDislikeCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CommentAttributeUpdatedAvroModel build() {
      try {
        CommentAttributeUpdatedAvroModel record = new CommentAttributeUpdatedAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.likesCount = fieldSetFlags()[1] ? this.likesCount : (java.lang.Integer) defaultValue(fields()[1]);
        record.dislikeCount = fieldSetFlags()[2] ? this.dislikeCount : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CommentAttributeUpdatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CommentAttributeUpdatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CommentAttributeUpdatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CommentAttributeUpdatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










